site_name: PSFPL
repo_url: https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_ModuleName %>
site_author: <%= $PLASTER_PARAM_FullName %>
edit_uri: edit/master/docs/
copyright: "AutoDocumentsExample is licensed under the <a href='https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_ModuleName %>/raw/master/LICENSE'>MIT license</a>"
theme: readthedocs
pages:
  - Home: index.md
